name: new

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-14

    steps:
      # ensure we use the latest xcode version (kinda redundant i guess)
      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest-stable
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Default Scheme
        run: |
          cd toggleMute
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          cd toggleMute
          #if [ $scheme = default ]; then scheme=$(cat default); fi
          #if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          #file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          #xcodebuild clean build analyze -scheme "$scheme" -"$filetype_parameter" "$file_to_build" | xcpretty
          #if [ "${PIPESTATUS[0]}" -ne 0 ] ; then exit ${PIPESTATUS[0]} ; fi
          #xcodebuild archive -scheme "$scheme" -archivePath App.xcarchive
          #ls -la App.xcarchive/Products/Applications
          #hdiutil create -volname "toggleMute" -srcfolder "App.xcarchive/Products/Applications/toggleMute.app" -ov -format UDZO "../toggleMute.dmg"
          #ls -la ..
          echo ${RANDOM} > ../toggleMute.dmg
          echo "dmg_checksum=$(shasum -a 256 -b "../toggleMute.dmg" | awk '{print $1 }')" >> $GITHUB_OUTPUT
      - uses: fwilhe2/bump-version@main
        id: bump
        with:
          component: ${{ github.event.inputs.component }}
      - run: echo "Bumped version is ${{ steps.bump.outputs.newVersion }}"
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.bump.outputs.newVersion }}
      #- run: git tag ${{ steps.bump.outputs.newVersion }} || true
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "toggleMute.dmg"
          body: "SHA256sum: ${{ steps.Build.outputs.dmg_checksum}}"
          name: ${{ steps.bump.outputs.newVersion }}
          commit: $GITHUB_SHA
          tag: ${{ steps.bump.outputs.newVersion }}
