name: create release and bump cask version

on:
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout testing
        uses: actions/checkout@v4
      
      - name: Get current version
        run: |
          ls -la

      # - name: Checkout homebrew-testing
      #   uses: actions/checkout@v4
      #   with:
      #     repository: 'satrik/homebrew-testing'
      #     token: ${{ secrets.CASK_REPO_TOKEN }}

      # - name: Bump version and update hash
      #   run: |
      #     sed -i 's/^  version .*/  version "0.2"/' ${{ github.workspace }}/Casks/testing.rb
      #     sed -i 's/^  sha256 .*/  sha256 "123486279a93d519acc8dabbdd2c9aadb6682bbd7533a4edb5ef6ca4cdaa9125"/' ${{ github.workspace }}/Casks/testing.rb

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ secrets.CASK_REPO_TOKEN }}
      #     commit-message: Update version of homebrew cask
      #     delete-branch: true
      #     title: 'Update version'
      #     labels: update
      #     draft: false
