name: create release and bump cask version

on:
  workflow_dispatch:

jobs:

  bump-cask:
    runs-on: macos-latest
    steps:
    - uses: macauley/action-homebrew-bump-cask@v1
      with:
        # required, custom GitHub access token with only the 'public_repo' scope enabled
        token: ${{secrets.CASK_REPO_TOKEN}}
        # bump all outdated casks in this tap
        tap: satrik/homebrew-testing
        # Cask name, required
        cask: testing
        # Optional, will be determined automatically
        tag: ${{github.ref}}
        # Optional, will be determined automatically
        revision: ${{github.sha}}
        # Optional, if don't want to check for already open PRs
        force: false
