name: create release and bump cask version

on:
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:

      - name: checkout testing
        uses: actions/checkout@v4

      - name: Set color
        id: color-selector
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"

      - name: get current version
        id: get-current-version-x
        run: |
          echo "CURRENT_VERSION=$(cat toggleMute/toggleMute.xcodeproj/project.pbxproj | grep -m1 'MARKETING_VERSION' | cut -d'=' -f2 | tr -d ';' | tr -d ' ')" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: get latest tag 
        id: get-latest-tag-x
        run: |
          echo "LATEST_TAG=$(git tag --sort=committerdate | tail -1)" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

      - name: print 
        run: |
          echo "CURRENT_VERSION ${{ steps.get-current-version-x.CURRENT_VERSION }}"
          echo "LATEST_TAG ${{ steps.get-latest-tag-x.outputs.LATEST_TAG }}"
      
      - name: get current version
        id: get-current-version
        run: |
          CURRENT_VERSION=$(cat toggleMute/toggleMute.xcodeproj/project.pbxproj | grep -m1 'MARKETING_VERSION' | cut -d'=' -f2 | tr -d ';' | tr -d ' ')
          cat toggleMute/toggleMute.xcodeproj/project.pbxproj | grep -m1 'MARKETING_VERSION' | cut -d'=' -f2 | tr -d ';' | tr -d ' '

      - name: get latest tag 
        id: get-latest-tag
        run: |
          LATEST_TAG=$(git tag --sort=committerdate | tail -1)
          git tag --sort=committerdate | tail -1

      - name: print 
        run: |
          echo "CURRENT_VERSION $CURRENT_VERSION"
          echo "LATEST_TAG $LATEST_TAG"
          
      # - name: Checkout homebrew-testing
      #   uses: actions/checkout@v4
      #   with:
      #     repository: 'satrik/homebrew-testing'
      #     token: ${{ secrets.CASK_REPO_TOKEN }}

      # - name: Bump version and update hash
      #   run: |
      #     sed -i 's/^  version .*/  version "0.2"/' ${{ github.workspace }}/Casks/testing.rb
      #     sed -i 's/^  sha256 .*/  sha256 "123486279a93d519acc8dabbdd2c9aadb6682bbd7533a4edb5ef6ca4cdaa9125"/' ${{ github.workspace }}/Casks/testing.rb

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ secrets.CASK_REPO_TOKEN }}
      #     commit-message: Update version of homebrew cask
      #     delete-branch: true
      #     title: 'Update version'
      #     labels: update
      #     draft: false
