name: create release and bump cask version

on:
  workflow_dispatch:

jobs:

  bump-cask:
    runs-on: macos-latest
    steps:
    - uses: macauley/action-homebrew-bump-cask@v1
      with:
        # required, custom GitHub access token with only the 'public_repo' scope enabled
        token: ${{secrets.CASK_REPO_TOKEN}}
        # Cask name, required
        cask: testing
        tap: satrik/testing
        # Optional, if don't want to check for already open PRs
        force: false
        livecheck: false
